# vim: ts=2:sw=2

- hosts: all
  tasks:
    - name: regolith apt key
      become: yes
      apt_key:
        state: present
        data: "{{ lookup('file', 'regolith.key') }}"

    - name: regolith apt repository
      become: yes
      apt_repository:
        state: present
        repo: deb [arch=amd64] http://regolith-release-ubuntu-jammy-amd64.s3.amazonaws.com jammy main
        filename: regolith

    - name: install regolith
      become: yes
      apt:
        cache_valid_time: 3600
        install_recommends: yes
        name: regolith-desktop
        state: present

    - name: install lightdm
      become: yes
      apt:
        state: present
        name: lightdm

    # TODO: look into the package regolith-lightdm-config

    - name: set lightdm as default login manager
      become: yes
      debconf:
        name: gdm3
        question: shared/default-x-display-manager
        value: lightdm
        vtype: select


