#!/bin/sh

#FIXME: Everything here can be rsynced instead. Do that, and consider if it should be done by an ansible script instead

fetch='wget -r -nc -np -nv -x -nH -e robots=off -l 6 -R "index.html*"'

#$fetch http://de.archive.ubuntu.com/ubuntu/dists/jammy/;
#$fetch http://de.archive.ubuntu.com/ubuntu/dists/jammy-security/;
#$fetch http://de.archive.ubuntu.com/ubuntu/dists/jammy-updates/;
#$fetch http://de.archive.ubuntu.com/ubuntu/ls-lR.gz;

# podman mirror
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/s/setuptools/python3-setuptools_59.6.0-1.2_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/p/pyrsistent/python3-pyrsistent_0.18.1-1build1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/p/python-jsonschema/python3-jsonschema_3.2.0-0ubuntu2_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/t/texttable/python3-texttable_1.6.4-1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/d/docker-compose/docker-compose_1.29.2-1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/a/appstream-glib/libappstream-glib8_0.7.18-2_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/f/fuse/libfuse2_2.9.9-5ubuntu3_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/m/malcontent/libmalcontent-0-0_0.10.4-1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/f/flatpak/flatpak_1.12.7-1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/f/fuse-overlayfs/fuse-overlayfs_1.7.1-1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/libe/liberror-perl/liberror-perl_0.17029-1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/git/git-man_2.34.1-1ubuntu1.2_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/git/git_2.34.1-1ubuntu1.2_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/golang-github-containers-dnsname/golang-github-containernetworking-plugin-dnsname_1.3.1%2bds1-2_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/libs/libslirp/libslirp0_4.6.1-1build1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/libp/libpod/podman_3.4.4%2bds1-1ubuntu1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/libp/libpod/podman-docker_3.4.4%2bds1-1ubuntu1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/golang-github-containers-toolbox/podman-toolbox_0.0.99.2-2ubuntu1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/s/slirp4netns/slirp4netns_1.0.1-2_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/u/ubuntu-fan/ubuntu-fan_0.12.16_all.deb


# neovim mirror
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/l/luajit/libluajit-5.1-common_2.1.0%7ebeta3%2bdfsg-6_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/l/luajit/libluajit-5.1-2_2.1.0%7ebeta3%2bdfsg-6_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/t/tree-sitter/libtree-sitter0_0.20.3-1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/u/unibilium/libunibilium4_2.1.0-1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/l/lua-luv/lua-luv_1.36.0-0-1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/p/python-msgpack/python3-msgpack_1.0.3-1build1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/p/python-greenlet/python3-greenlet_1.1.2-3build1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/p/python-pynvim/python3-pynvim_0.4.2-1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/p/python-pynvim/python3-neovim_0.4.2-1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/x/xclip/xclip_0.13-2_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/m/msgpack-c/libmsgpackc2_3.3.0-4_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/libt/libtermkey/libtermkey1_0.22-1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/libv/libvterm/libvterm0_0.1.4-1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/n/neovim/neovim-runtime_0.6.1-3_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/n/neovim/neovim_0.6.1-3_amd64.deb


# zsh
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/z/zsh/zsh-common_5.8.1-1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/z/zsh/zsh_5.8.1-1_amd64.deb


# build essentials and dependencies
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/b/binutils/binutils-common_2.38-3ubuntu1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/b/binutils/libbinutils_2.38-3ubuntu1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/b/binutils/libctf-nobfd0_2.38-3ubuntu1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/b/binutils/libctf0_2.38-3ubuntu1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/b/binutils/binutils-x86-64-linux-gnu_2.38-3ubuntu1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/b/binutils/binutils_2.38-3ubuntu1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/b/binutils-mipsen/binutils-mipsisa32r6-linux-gnu_2.38-1ubuntu1cross2_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/b/binutils-mipsen/binutils-mipsisa32r6el-linux-gnu_2.38-1ubuntu1cross2_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/b/binutils-mipsen/binutils-mipsisa64r6-linux-gnuabi64_2.38-1ubuntu1cross2_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/b/binutils-mipsen/binutils-mipsisa64r6el-linux-gnuabi64_2.38-1ubuntu1cross2_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/b/binutils/binutils-riscv64-linux-gnu_2.38-3ubuntu1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/glibc/libc-dev-bin_2.35-0ubuntu3_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/l/linux/linux-libc-dev_5.15.0-33.34_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/libx/libxcrypt/libcrypt-dev_4.4.27-1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/r/rpcsvc-proto/rpcsvc-proto_1.4.2-0ubuntu6_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/libt/libtirpc/libtirpc-dev_1.3.2-2build1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/libn/libnsl/libnsl-dev_1.3.0-2build2_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/glibc/libc6-dev_2.35-0ubuntu3_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-12/libcc1-0_12-20220319-1ubuntu1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-12/libitm1_12-20220319-1ubuntu1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-12/libatomic1_12-20220319-1ubuntu1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-11/libasan6_11.2.0-19ubuntu1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-12/liblsan0_12-20220319-1ubuntu1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-11/libtsan0_11.2.0-19ubuntu1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-12/libubsan1_12-20220319-1ubuntu1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-12/libquadmath0_12-20220319-1ubuntu1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-11/libgcc-11-dev_11.2.0-19ubuntu1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-11/gcc-11_11.2.0-19ubuntu1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-defaults/gcc_11.2.0-1ubuntu1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-11/libstdc%2b%2b-11-dev_11.2.0-19ubuntu1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-11/g%2b%2b-11_11.2.0-19ubuntu1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-defaults/g%2b%2b_11.2.0-1ubuntu1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/m/make-dfsg/make_4.3-4.1build1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/d/dpkg/libdpkg-perl_1.21.1ubuntu2_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/l/lto-disabled-list/lto-disabled-list_24_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/d/dpkg/dpkg-dev_1.21.1ubuntu2_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/b/build-essential/build-essential_12.9ubuntu3_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/gcc-10-mips-linux-gnu-base_10.3.0-1ubuntu1cross2_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/cpp-10-mips-linux-gnu_10.3.0-1ubuntu1cross2_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/gcc-10-mips64-linux-gnuabi64-base_10.3.0-1ubuntu1cross2_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/cpp-10-mips64-linux-gnuabi64_10.3.0-1ubuntu1cross2_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/gcc-10-mips64el-linux-gnuabi64-base_10.3.0-1ubuntu1cross2_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/cpp-10-mips64el-linux-gnuabi64_10.3.0-1ubuntu1cross2_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/gcc-10-mipsel-linux-gnu-base_10.3.0-1ubuntu1cross2_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/cpp-10-mipsel-linux-gnu_10.3.0-1ubuntu1cross2_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/gcc-10-mipsisa32r6-linux-gnu-base_10.3.0-1ubuntu1cross2_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/cpp-10-mipsisa32r6-linux-gnu_10.3.0-1ubuntu1cross2_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/gcc-10-mipsisa32r6el-linux-gnu-base_10.3.0-1ubuntu1cross2_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/cpp-10-mipsisa32r6el-linux-gnu_10.3.0-1ubuntu1cross2_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/gcc-10-mipsisa64r6-linux-gnuabi64-base_10.3.0-1ubuntu1cross2_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/cpp-10-mipsisa64r6-linux-gnuabi64_10.3.0-1ubuntu1cross2_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/gcc-10-mipsisa64r6el-linux-gnuabi64-base_10.3.0-1ubuntu1cross2_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/cpp-10-mipsisa64r6el-linux-gnuabi64_10.3.0-1ubuntu1cross2_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-11-cross/gcc-11-aarch64-linux-gnu-base_11.2.0-17ubuntu1cross1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-11-cross/cpp-11-aarch64-linux-gnu_11.2.0-17ubuntu1cross1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-11-cross/gcc-11-arm-linux-gnueabi-base_11.2.0-17ubuntu1cross1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-11-cross/cpp-11-arm-linux-gnueabi_11.2.0-17ubuntu1cross1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-11-cross/gcc-11-arm-linux-gnueabihf-base_11.2.0-17ubuntu1cross1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-11-cross/cpp-11-arm-linux-gnueabihf_11.2.0-17ubuntu1cross1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-11-cross/gcc-11-i686-linux-gnu-base_11.2.0-17ubuntu1cross1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-11-cross/cpp-11-i686-linux-gnu_11.2.0-17ubuntu1cross1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-11-cross/gcc-11-powerpc-linux-gnu-base_11.2.0-17ubuntu1cross1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-11-cross/cpp-11-powerpc-linux-gnu_11.2.0-17ubuntu1cross1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-11-cross/gcc-11-powerpc64le-linux-gnu-base_11.2.0-17ubuntu1cross1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-11-cross/cpp-11-powerpc64le-linux-gnu_11.2.0-17ubuntu1cross1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-11-cross-ports/gcc-11-riscv64-linux-gnu-base_11.2.0-16ubuntu1cross1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-11-cross-ports/cpp-11-riscv64-linux-gnu_11.2.0-16ubuntu1cross1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-11-cross/gcc-11-s390x-linux-gnu-base_11.2.0-17ubuntu1cross1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-11-cross/cpp-11-s390x-linux-gnu_11.2.0-17ubuntu1cross1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-defaults/cpp-aarch64-linux-gnu_11.2.0-1ubuntu1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-defaults/cpp-arm-linux-gnueabi_11.2.0-1ubuntu1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-defaults/cpp-arm-linux-gnueabihf_11.2.0-1ubuntu1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-defaults/cpp-i686-linux-gnu_11.2.0-1ubuntu1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-defaults-mipsen/cpp-mips-linux-gnu_10.2.0-1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-defaults-mipsen/cpp-mips64-linux-gnuabi64_10.2.0-1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-defaults-mipsen/cpp-mips64el-linux-gnuabi64_10.2.0-1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-defaults-mipsen/cpp-mipsel-linux-gnu_10.2.0-1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-defaults-mipsen/cpp-mipsisa32r6-linux-gnu_10.2.0-1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-defaults-mipsen/cpp-mipsisa32r6el-linux-gnu_10.2.0-1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-defaults-mipsen/cpp-mipsisa64r6-linux-gnuabi64_10.2.0-1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-defaults-mipsen/cpp-mipsisa64r6el-linux-gnuabi64_10.2.0-1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-defaults/cpp-powerpc-linux-gnu_11.2.0-1ubuntu1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-defaults/cpp-powerpc64le-linux-gnu_11.2.0-1ubuntu1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-defaults-ports/cpp-riscv64-linux-gnu_11.2.0--1ubuntu1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-defaults/cpp-s390x-linux-gnu_11.2.0-1ubuntu1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/libc/libconfig-inifiles-perl/libconfig-inifiles-perl_3.000003-1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/libi/libio-string-perl/libio-string-perl_1.08-3.1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/libx/libxml-namespacesupport-perl/libxml-namespacesupport-perl_1.12-1.1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/libx/libxml-sax-base-perl/libxml-sax-base-perl_1.09-1.1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/libx/libxml-sax-perl/libxml-sax-perl_1.02%2bdfsg-3_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/libx/libxml-libxml-perl/libxml-libxml-perl_2.0207%2bdfsg%2breally%2b2.0134-1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/libx/libxml-sax-expat-perl/libxml-sax-expat-perl_0.51-1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/libx/libxml-simple-perl/libxml-simple-perl_2.25-1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/liby/libyaml-perl/libyaml-perl_1.30-1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/libc/libconfig-auto-perl/libconfig-auto-perl_0.44-1.1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/libf/libfile-which-perl/libfile-which-perl_1.23-1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/libf/libfile-homedir-perl/libfile-homedir-perl_1.006-1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/d/dpkg-cross/libdebian-dpkgcross-perl_2.6.18%2bnmu2_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/d/dpkg-cross/cross-config_2.6.18%2bnmu2_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/d/dpkg-cross/dpkg-cross_2.6.18%2bnmu2_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/b/build-essential/crossbuild-essential-amd64_12.9ubuntu3_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/b/binutils/binutils-aarch64-linux-gnu_2.38-3ubuntu1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-11-cross/gcc-11-cross-base_11.2.0-17ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-12-cross/gcc-12-cross-base_12-20220222-1ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/c/cross-toolchain-base/libc6-arm64-cross_2.35-0ubuntu1cross3_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-12-cross/libgcc-s1-arm64-cross_12-20220222-1ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-12-cross/libgomp1-arm64-cross_12-20220222-1ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-12-cross/libitm1-arm64-cross_12-20220222-1ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-12-cross/libatomic1-arm64-cross_12-20220222-1ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-11-cross/libasan6-arm64-cross_11.2.0-17ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-12-cross/liblsan0-arm64-cross_12-20220222-1ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-11-cross/libtsan0-arm64-cross_11.2.0-17ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-12-cross/libstdc%2b%2b6-arm64-cross_12-20220222-1ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-12-cross/libubsan1-arm64-cross_12-20220222-1ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-12-cross/libhwasan0-arm64-cross_12-20220222-1ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-11-cross/libgcc-11-dev-arm64-cross_11.2.0-17ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-11-cross/gcc-11-aarch64-linux-gnu_11.2.0-17ubuntu1cross1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-defaults/gcc-aarch64-linux-gnu_11.2.0-1ubuntu1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/c/cross-toolchain-base/linux-libc-dev-arm64-cross_5.15.0-22.22cross3_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/c/cross-toolchain-base/libc6-dev-arm64-cross_2.35-0ubuntu1cross3_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-11-cross/libstdc%2b%2b-11-dev-arm64-cross_11.2.0-17ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-11-cross/g%2b%2b-11-aarch64-linux-gnu_11.2.0-17ubuntu1cross1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-defaults/g%2b%2b-aarch64-linux-gnu_11.2.0-1ubuntu1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/b/build-essential/crossbuild-essential-arm64_12.9ubuntu3_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/b/binutils/binutils-arm-linux-gnueabi_2.38-3ubuntu1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/c/cross-toolchain-base/libc6-armel-cross_2.35-0ubuntu1cross3_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-12-cross/libgcc-s1-armel-cross_12-20220222-1ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-12-cross/libgomp1-armel-cross_12-20220222-1ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-12-cross/libatomic1-armel-cross_12-20220222-1ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-11-cross/libasan6-armel-cross_11.2.0-17ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-12-cross/libstdc%2b%2b6-armel-cross_12-20220222-1ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-12-cross/libubsan1-armel-cross_12-20220222-1ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-11-cross/libgcc-11-dev-armel-cross_11.2.0-17ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-11-cross/gcc-11-arm-linux-gnueabi_11.2.0-17ubuntu1cross1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-defaults/gcc-arm-linux-gnueabi_11.2.0-1ubuntu1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/c/cross-toolchain-base/linux-libc-dev-armel-cross_5.15.0-22.22cross3_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/c/cross-toolchain-base/libc6-dev-armel-cross_2.35-0ubuntu1cross3_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-11-cross/libstdc%2b%2b-11-dev-armel-cross_11.2.0-17ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-11-cross/g%2b%2b-11-arm-linux-gnueabi_11.2.0-17ubuntu1cross1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-defaults/g%2b%2b-arm-linux-gnueabi_11.2.0-1ubuntu1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/b/build-essential/crossbuild-essential-armel_12.9ubuntu3_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/b/binutils/binutils-arm-linux-gnueabihf_2.38-3ubuntu1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/c/cross-toolchain-base/libc6-armhf-cross_2.35-0ubuntu1cross3_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-12-cross/libgcc-s1-armhf-cross_12-20220222-1ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-12-cross/libgomp1-armhf-cross_12-20220222-1ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-12-cross/libatomic1-armhf-cross_12-20220222-1ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-11-cross/libasan6-armhf-cross_11.2.0-17ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-12-cross/libstdc%2b%2b6-armhf-cross_12-20220222-1ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-12-cross/libubsan1-armhf-cross_12-20220222-1ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-11-cross/libgcc-11-dev-armhf-cross_11.2.0-17ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-11-cross/gcc-11-arm-linux-gnueabihf_11.2.0-17ubuntu1cross1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-defaults/gcc-arm-linux-gnueabihf_11.2.0-1ubuntu1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/c/cross-toolchain-base/linux-libc-dev-armhf-cross_5.15.0-22.22cross3_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/c/cross-toolchain-base/libc6-dev-armhf-cross_2.35-0ubuntu1cross3_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-11-cross/libstdc%2b%2b-11-dev-armhf-cross_11.2.0-17ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-11-cross/g%2b%2b-11-arm-linux-gnueabihf_11.2.0-17ubuntu1cross1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-defaults/g%2b%2b-arm-linux-gnueabihf_11.2.0-1ubuntu1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/b/build-essential/crossbuild-essential-armhf_12.9ubuntu3_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/b/binutils/binutils-i686-linux-gnu_2.38-3ubuntu1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/c/cross-toolchain-base/libc6-i386-cross_2.35-0ubuntu1cross3_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-12-cross/libgcc-s1-i386-cross_12-20220222-1ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-12-cross/libgomp1-i386-cross_12-20220222-1ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-12-cross/libitm1-i386-cross_12-20220222-1ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-12-cross/libatomic1-i386-cross_12-20220222-1ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-11-cross/libasan6-i386-cross_11.2.0-17ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-12-cross/libstdc%2b%2b6-i386-cross_12-20220222-1ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-12-cross/libubsan1-i386-cross_12-20220222-1ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-12-cross/libquadmath0-i386-cross_12-20220222-1ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-11-cross/libgcc-11-dev-i386-cross_11.2.0-17ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-11-cross/gcc-11-i686-linux-gnu_11.2.0-17ubuntu1cross1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-defaults/gcc-i686-linux-gnu_11.2.0-1ubuntu1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/c/cross-toolchain-base/linux-libc-dev-i386-cross_5.15.0-22.22cross3_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/c/cross-toolchain-base/libc6-dev-i386-cross_2.35-0ubuntu1cross3_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-11-cross/libstdc%2b%2b-11-dev-i386-cross_11.2.0-17ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-11-cross/g%2b%2b-11-i686-linux-gnu_11.2.0-17ubuntu1cross1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-defaults/g%2b%2b-i686-linux-gnu_11.2.0-1ubuntu1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/b/build-essential/crossbuild-essential-i386_12.9ubuntu3_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/b/binutils-mipsen/binutils-mips-linux-gnu_2.38-1ubuntu1cross2_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/gcc-10-cross-base-mipsen_10.3.0-1ubuntu1cross2_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/c/cross-toolchain-base-mipsen/libc6-mips-cross_2.35-0ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/libgcc-s1-mips-cross_10.3.0-1ubuntu1cross2_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/libgomp1-mips-cross_10.3.0-1ubuntu1cross2_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/libatomic1-mips-cross_10.3.0-1ubuntu1cross2_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/libgcc-10-dev-mips-cross_10.3.0-1ubuntu1cross2_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/gcc-10-mips-linux-gnu_10.3.0-1ubuntu1cross2_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-defaults-mipsen/gcc-mips-linux-gnu_10.2.0-1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/libstdc%2b%2b6-mips-cross_10.3.0-1ubuntu1cross2_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/c/cross-toolchain-base-mipsen/linux-libc-dev-mips-cross_5.15.0-18.18cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/c/cross-toolchain-base-mipsen/libc6-dev-mips-cross_2.35-0ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/libstdc%2b%2b-10-dev-mips-cross_10.3.0-1ubuntu1cross2_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/g%2b%2b-10-mips-linux-gnu_10.3.0-1ubuntu1cross2_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-defaults-mipsen/g%2b%2b-mips-linux-gnu_10.2.0-1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/b/build-essential-mipsen/crossbuild-essential-mips_12.9_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/b/binutils-mipsen/binutils-mips64-linux-gnuabi64_2.38-1ubuntu1cross2_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/c/cross-toolchain-base-mipsen/libc6-mips64-cross_2.35-0ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/libgcc-s1-mips64-cross_10.3.0-1ubuntu1cross2_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/libgomp1-mips64-cross_10.3.0-1ubuntu1cross2_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/libatomic1-mips64-cross_10.3.0-1ubuntu1cross2_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/libgcc-10-dev-mips64-cross_10.3.0-1ubuntu1cross2_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/gcc-10-mips64-linux-gnuabi64_10.3.0-1ubuntu1cross2_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-defaults-mipsen/gcc-mips64-linux-gnuabi64_10.2.0-1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/libstdc%2b%2b6-mips64-cross_10.3.0-1ubuntu1cross2_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/c/cross-toolchain-base-mipsen/linux-libc-dev-mips64-cross_5.15.0-18.18cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/c/cross-toolchain-base-mipsen/libc6-dev-mips64-cross_2.35-0ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/libstdc%2b%2b-10-dev-mips64-cross_10.3.0-1ubuntu1cross2_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/g%2b%2b-10-mips64-linux-gnuabi64_10.3.0-1ubuntu1cross2_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-defaults-mipsen/g%2b%2b-mips64-linux-gnuabi64_10.2.0-1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/b/build-essential-mipsen/crossbuild-essential-mips64_12.9_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/b/binutils-mipsen/binutils-mips64el-linux-gnuabi64_2.38-1ubuntu1cross2_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/c/cross-toolchain-base-mipsen/libc6-mips64el-cross_2.35-0ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/libgcc-s1-mips64el-cross_10.3.0-1ubuntu1cross2_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/libgomp1-mips64el-cross_10.3.0-1ubuntu1cross2_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/libatomic1-mips64el-cross_10.3.0-1ubuntu1cross2_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/libgcc-10-dev-mips64el-cross_10.3.0-1ubuntu1cross2_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/gcc-10-mips64el-linux-gnuabi64_10.3.0-1ubuntu1cross2_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-defaults-mipsen/gcc-mips64el-linux-gnuabi64_10.2.0-1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/libstdc%2b%2b6-mips64el-cross_10.3.0-1ubuntu1cross2_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/c/cross-toolchain-base-mipsen/linux-libc-dev-mips64el-cross_5.15.0-18.18cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/c/cross-toolchain-base-mipsen/libc6-dev-mips64el-cross_2.35-0ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/libstdc%2b%2b-10-dev-mips64el-cross_10.3.0-1ubuntu1cross2_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/g%2b%2b-10-mips64el-linux-gnuabi64_10.3.0-1ubuntu1cross2_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-defaults-mipsen/g%2b%2b-mips64el-linux-gnuabi64_10.2.0-1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/b/build-essential-mipsen/crossbuild-essential-mips64el_12.9_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/c/cross-toolchain-base-mipsen/libc6-mips64r6-cross_2.35-0ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/libgcc-s1-mips64r6-cross_10.3.0-1ubuntu1cross2_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/libgomp1-mips64r6-cross_10.3.0-1ubuntu1cross2_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/libatomic1-mips64r6-cross_10.3.0-1ubuntu1cross2_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/libgcc-10-dev-mips64r6-cross_10.3.0-1ubuntu1cross2_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/gcc-10-mipsisa64r6-linux-gnuabi64_10.3.0-1ubuntu1cross2_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-defaults-mipsen/gcc-mipsisa64r6-linux-gnuabi64_10.2.0-1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/libstdc%2b%2b6-mips64r6-cross_10.3.0-1ubuntu1cross2_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/c/cross-toolchain-base-mipsen/linux-libc-dev-mips64r6-cross_5.15.0-18.18cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/c/cross-toolchain-base-mipsen/libc6-dev-mips64r6-cross_2.35-0ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/libstdc%2b%2b-10-dev-mips64r6-cross_10.3.0-1ubuntu1cross2_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/g%2b%2b-10-mipsisa64r6-linux-gnuabi64_10.3.0-1ubuntu1cross2_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-defaults-mipsen/g%2b%2b-mipsisa64r6-linux-gnuabi64_10.2.0-1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/b/build-essential-mipsen/crossbuild-essential-mips64r6_12.9_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/c/cross-toolchain-base-mipsen/libc6-mips64r6el-cross_2.35-0ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/libgcc-s1-mips64r6el-cross_10.3.0-1ubuntu1cross2_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/libgomp1-mips64r6el-cross_10.3.0-1ubuntu1cross2_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/libatomic1-mips64r6el-cross_10.3.0-1ubuntu1cross2_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/libgcc-10-dev-mips64r6el-cross_10.3.0-1ubuntu1cross2_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/gcc-10-mipsisa64r6el-linux-gnuabi64_10.3.0-1ubuntu1cross2_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-defaults-mipsen/gcc-mipsisa64r6el-linux-gnuabi64_10.2.0-1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/libstdc%2b%2b6-mips64r6el-cross_10.3.0-1ubuntu1cross2_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/c/cross-toolchain-base-mipsen/linux-libc-dev-mips64r6el-cross_5.15.0-18.18cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/c/cross-toolchain-base-mipsen/libc6-dev-mips64r6el-cross_2.35-0ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/libstdc%2b%2b-10-dev-mips64r6el-cross_10.3.0-1ubuntu1cross2_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/g%2b%2b-10-mipsisa64r6el-linux-gnuabi64_10.3.0-1ubuntu1cross2_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-defaults-mipsen/g%2b%2b-mipsisa64r6el-linux-gnuabi64_10.2.0-1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/b/build-essential-mipsen/crossbuild-essential-mips64r6el_12.9_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/b/binutils-mipsen/binutils-mipsel-linux-gnu_2.38-1ubuntu1cross2_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/c/cross-toolchain-base-mipsen/libc6-mipsel-cross_2.35-0ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/libgcc-s1-mipsel-cross_10.3.0-1ubuntu1cross2_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/libgomp1-mipsel-cross_10.3.0-1ubuntu1cross2_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/libatomic1-mipsel-cross_10.3.0-1ubuntu1cross2_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/libgcc-10-dev-mipsel-cross_10.3.0-1ubuntu1cross2_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/gcc-10-mipsel-linux-gnu_10.3.0-1ubuntu1cross2_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-defaults-mipsen/gcc-mipsel-linux-gnu_10.2.0-1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/libstdc%2b%2b6-mipsel-cross_10.3.0-1ubuntu1cross2_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/c/cross-toolchain-base-mipsen/linux-libc-dev-mipsel-cross_5.15.0-18.18cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/c/cross-toolchain-base-mipsen/libc6-dev-mipsel-cross_2.35-0ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/libstdc%2b%2b-10-dev-mipsel-cross_10.3.0-1ubuntu1cross2_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/g%2b%2b-10-mipsel-linux-gnu_10.3.0-1ubuntu1cross2_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-defaults-mipsen/g%2b%2b-mipsel-linux-gnu_10.2.0-1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/b/build-essential-mipsen/crossbuild-essential-mipsel_12.9_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/c/cross-toolchain-base-mipsen/libc6-mipsr6-cross_2.35-0ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/libgcc-s1-mipsr6-cross_10.3.0-1ubuntu1cross2_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/libgomp1-mipsr6-cross_10.3.0-1ubuntu1cross2_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/libatomic1-mipsr6-cross_10.3.0-1ubuntu1cross2_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/libgcc-10-dev-mipsr6-cross_10.3.0-1ubuntu1cross2_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/gcc-10-mipsisa32r6-linux-gnu_10.3.0-1ubuntu1cross2_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-defaults-mipsen/gcc-mipsisa32r6-linux-gnu_10.2.0-1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/libstdc%2b%2b6-mipsr6-cross_10.3.0-1ubuntu1cross2_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/c/cross-toolchain-base-mipsen/linux-libc-dev-mipsr6-cross_5.15.0-18.18cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/c/cross-toolchain-base-mipsen/libc6-dev-mipsr6-cross_2.35-0ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/libstdc%2b%2b-10-dev-mipsr6-cross_10.3.0-1ubuntu1cross2_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/g%2b%2b-10-mipsisa32r6-linux-gnu_10.3.0-1ubuntu1cross2_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-defaults-mipsen/g%2b%2b-mipsisa32r6-linux-gnu_10.2.0-1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/b/build-essential-mipsen/crossbuild-essential-mipsr6_12.9_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/c/cross-toolchain-base-mipsen/libc6-mipsr6el-cross_2.35-0ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/libgcc-s1-mipsr6el-cross_10.3.0-1ubuntu1cross2_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/libgomp1-mipsr6el-cross_10.3.0-1ubuntu1cross2_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/libatomic1-mipsr6el-cross_10.3.0-1ubuntu1cross2_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/libgcc-10-dev-mipsr6el-cross_10.3.0-1ubuntu1cross2_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/gcc-10-mipsisa32r6el-linux-gnu_10.3.0-1ubuntu1cross2_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-defaults-mipsen/gcc-mipsisa32r6el-linux-gnu_10.2.0-1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/libstdc%2b%2b6-mipsr6el-cross_10.3.0-1ubuntu1cross2_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/c/cross-toolchain-base-mipsen/linux-libc-dev-mipsr6el-cross_5.15.0-18.18cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/c/cross-toolchain-base-mipsen/libc6-dev-mipsr6el-cross_2.35-0ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/libstdc%2b%2b-10-dev-mipsr6el-cross_10.3.0-1ubuntu1cross2_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross-mipsen/g%2b%2b-10-mipsisa32r6el-linux-gnu_10.3.0-1ubuntu1cross2_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-defaults-mipsen/g%2b%2b-mipsisa32r6el-linux-gnu_10.2.0-1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/b/build-essential-mipsen/crossbuild-essential-mipsr6el_12.9_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/b/binutils/binutils-powerpc-linux-gnu_2.38-3ubuntu1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/c/cross-toolchain-base/libc6-powerpc-cross_2.35-0ubuntu1cross3_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-12-cross/libgcc-s1-powerpc-cross_12-20220222-1ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-12-cross/libgomp1-powerpc-cross_12-20220222-1ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-12-cross/libatomic1-powerpc-cross_12-20220222-1ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-11-cross/libasan6-powerpc-cross_11.2.0-17ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-12-cross/libstdc%2b%2b6-powerpc-cross_12-20220222-1ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-12-cross/libubsan1-powerpc-cross_12-20220222-1ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-11-cross/libgcc-11-dev-powerpc-cross_11.2.0-17ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-11-cross/gcc-11-powerpc-linux-gnu_11.2.0-17ubuntu1cross1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-defaults/gcc-powerpc-linux-gnu_11.2.0-1ubuntu1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/c/cross-toolchain-base/linux-libc-dev-powerpc-cross_5.15.0-22.22cross3_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/c/cross-toolchain-base/libc6-dev-powerpc-cross_2.35-0ubuntu1cross3_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-11-cross/libstdc%2b%2b-11-dev-powerpc-cross_11.2.0-17ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-11-cross/g%2b%2b-11-powerpc-linux-gnu_11.2.0-17ubuntu1cross1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-defaults/g%2b%2b-powerpc-linux-gnu_11.2.0-1ubuntu1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/b/build-essential/crossbuild-essential-powerpc_12.9ubuntu3_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/b/binutils/binutils-powerpc64le-linux-gnu_2.38-3ubuntu1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/c/cross-toolchain-base/libc6-ppc64el-cross_2.35-0ubuntu1cross3_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-12-cross/libgcc-s1-ppc64el-cross_12-20220222-1ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-12-cross/libgomp1-ppc64el-cross_12-20220222-1ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-12-cross/libitm1-ppc64el-cross_12-20220222-1ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-12-cross/libatomic1-ppc64el-cross_12-20220222-1ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-11-cross/libasan6-ppc64el-cross_11.2.0-17ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-12-cross/liblsan0-ppc64el-cross_12-20220222-1ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-11-cross/libtsan0-ppc64el-cross_11.2.0-17ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-12-cross/libstdc%2b%2b6-ppc64el-cross_12-20220222-1ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-12-cross/libubsan1-ppc64el-cross_12-20220222-1ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-12-cross/libquadmath0-ppc64el-cross_12-20220222-1ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-11-cross/libgcc-11-dev-ppc64el-cross_11.2.0-17ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-11-cross/gcc-11-powerpc64le-linux-gnu_11.2.0-17ubuntu1cross1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-defaults/gcc-powerpc64le-linux-gnu_11.2.0-1ubuntu1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/c/cross-toolchain-base/linux-libc-dev-ppc64el-cross_5.15.0-22.22cross3_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/c/cross-toolchain-base/libc6-dev-ppc64el-cross_2.35-0ubuntu1cross3_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-11-cross/libstdc%2b%2b-11-dev-ppc64el-cross_11.2.0-17ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-11-cross/g%2b%2b-11-powerpc64le-linux-gnu_11.2.0-17ubuntu1cross1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-defaults/g%2b%2b-powerpc64le-linux-gnu_11.2.0-1ubuntu1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/b/build-essential/crossbuild-essential-ppc64el_12.9ubuntu3_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-11-cross-ports/gcc-11-cross-base-ports_11.2.0-16ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-12-cross-ports/gcc-12-cross-base-ports_12-20220302-1ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/c/cross-toolchain-base-ports/libc6-riscv64-cross_2.35-0ubuntu3cross4_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-12-cross-ports/libgcc-s1-riscv64-cross_12-20220302-1ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-12-cross-ports/libgomp1-riscv64-cross_12-20220302-1ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-12-cross-ports/libatomic1-riscv64-cross_12-20220302-1ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-11-cross-ports/libasan6-riscv64-cross_11.2.0-16ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-11-cross-ports/libgcc-11-dev-riscv64-cross_11.2.0-16ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-11-cross-ports/gcc-11-riscv64-linux-gnu_11.2.0-16ubuntu1cross1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-defaults-ports/gcc-riscv64-linux-gnu_11.2.0--1ubuntu1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-12-cross-ports/libstdc%2b%2b6-riscv64-cross_12-20220302-1ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/c/cross-toolchain-base-ports/linux-libc-dev-riscv64-cross_5.15.0-22.22cross4_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/c/cross-toolchain-base-ports/libc6-dev-riscv64-cross_2.35-0ubuntu3cross4_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-11-cross-ports/libstdc%2b%2b-11-dev-riscv64-cross_11.2.0-16ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-11-cross-ports/g%2b%2b-11-riscv64-linux-gnu_11.2.0-16ubuntu1cross1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-defaults-ports/g%2b%2b-riscv64-linux-gnu_11.2.0--1ubuntu1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/universe/b/build-essential/crossbuild-essential-riscv64_12.9ubuntu3_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/b/binutils/binutils-s390x-linux-gnu_2.38-3ubuntu1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/c/cross-toolchain-base/libc6-s390x-cross_2.35-0ubuntu1cross3_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-12-cross/libgcc-s1-s390x-cross_12-20220222-1ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-12-cross/libgomp1-s390x-cross_12-20220222-1ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-12-cross/libitm1-s390x-cross_12-20220222-1ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-12-cross/libatomic1-s390x-cross_12-20220222-1ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-11-cross/libasan6-s390x-cross_11.2.0-17ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-12-cross/libstdc%2b%2b6-s390x-cross_12-20220222-1ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-12-cross/libubsan1-s390x-cross_12-20220222-1ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-11-cross/libgcc-11-dev-s390x-cross_11.2.0-17ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-11-cross/gcc-11-s390x-linux-gnu_11.2.0-17ubuntu1cross1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-defaults/gcc-s390x-linux-gnu_11.2.0-1ubuntu1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/c/cross-toolchain-base/linux-libc-dev-s390x-cross_5.15.0-22.22cross3_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/c/cross-toolchain-base/libc6-dev-s390x-cross_2.35-0ubuntu1cross3_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-11-cross/libstdc%2b%2b-11-dev-s390x-cross_11.2.0-17ubuntu1cross1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-11-cross/g%2b%2b-11-s390x-linux-gnu_11.2.0-17ubuntu1cross1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/gcc-defaults/g%2b%2b-s390x-linux-gnu_11.2.0-1ubuntu1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/b/build-essential/crossbuild-essential-s390x_12.9ubuntu3_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/f/fakeroot/libfakeroot_1.28-1ubuntu1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/f/fakeroot/fakeroot_1.28-1ubuntu1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/liba/libalgorithm-diff-perl/libalgorithm-diff-perl_1.201-1_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/liba/libalgorithm-diff-xs-perl/libalgorithm-diff-xs-perl_0.04-6build3_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/liba/libalgorithm-merge-perl/libalgorithm-merge-perl_0.08-3_all.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/g/glibc/libc-devtools_2.35-0ubuntu3_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/libf/libfile-fcntllock-perl/libfile-fcntllock-perl_0.22-3build7_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/liby/libyaml-libyaml-perl/libyaml-libyaml-perl_0.83%2bds-1build1_amd64.deb
$fetch http://de.archive.ubuntu.com/ubuntu/pool/main/m/manpages/manpages-dev_5.10-1ubuntu1_all.deb


# regolith dependencies
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/a/ayatana-indicator-messages/libmessaging-menu0_22.2.0-1_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/f/fonts-font-awesome/fonts-font-awesome_5.0.10%2breally4.7.0%7edfsg-4.1_all.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/j/javascript-common/javascript-common_11%2bnmu1_all.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/libc/libcommon-sense-perl/libcommon-sense-perl_3.75-2build1_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/libj/libjsoncpp/libjsoncpp25_1.9.5-3_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/libj/libjson-xs-perl/libjson-xs-perl_4.030-1build3_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/libt/libtypes-serialiser-perl/libtypes-serialiser-perl_1.01-1_all.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/libu/liburing/liburing2_2.1-2build1_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/libx/libxcb/libxcb-composite0_1.14-3ubuntu3_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/libx/libxcb/libxcb-damage0_1.14-3ubuntu3_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/libx/libxcb/libxcb-xinerama0_1.14-3ubuntu3_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/n/node-jquery/libjs-jquery_3.6.0%2bdfsg%2b%7e3.5.13-1_all.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/p/plocate/mlocate_1.1.15-1ubuntu2_all.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/p/plocate/plocate_1.1.15-1ubuntu2_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/p/python-psutil/python3-psutil_5.9.0-1build1_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/p/python-setproctitle/python3-setproctitle_1.2.2-2build1_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/s/sphinx/libjs-sphinxdoc_4.3.2-1_all.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/s/sysstat/sysstat_12.5.2-2build2_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/u/underscore/libjs-underscore_1.13.2%7edfsg-2_all.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/x/xcb-util-wm/libxcb-ewmh2_0.4.1-1.1build2_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/universe/b/bamf/bamfdaemon_0.5.6%2b22.04.20220217-0ubuntu1_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/universe/b/bamf/libbamf3-2_0.5.6%2b22.04.20220217-0ubuntu1_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/universe/d/dex/dex_0.9.0-1_all.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/universe/f/faba-icon-theme/faba-icon-theme_4.3-1_all.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/universe/f/fcitx/libfcitx-config4_4.2.9.8-5_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/universe/f/fcitx/libfcitx-gclient1_4.2.9.8-5_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/universe/f/fcitx/libfcitx-utils0_4.2.9.8-5_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/universe/g/gnome-flashback/gnome-flashback_3.44.0-1ubuntu1_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/universe/g/gnome-flashback/gnome-flashback-common_3.44.0-1ubuntu1_all.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/universe/g/gnome-icon-theme/gnome-icon-theme_3.12.0-4_all.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/universe/g/gnome-panel/libgnome-panel0_3.44.0-1ubuntu1_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/universe/g/gnome-themes-extra/gnome-themes-standard_3.28-1ubuntu3_all.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/universe/g/gsettings-ubuntu-touch-schemas/accountsservice-ubuntu-schemas_0.0.7%2b21.10.20210712-0ubuntu2_all.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/universe/i/i3status/i3status_2.13-3_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/universe/i/ido/libido3-0.1-0_13.10.0%2b17.04.20161028-0ubuntu3_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/universe/i/indicator-applet/indicator-applet_12.10.2%2b20.10.20200915-0ubuntu1_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/universe/i/indicator-application/indicator-application_12.10.1%2b19.04.20190308.1-0ubuntu3_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/universe/i/indicator-appmenu/indicator-appmenu_15.02.0%2b20.10.20200617.2-0ubuntu1_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/universe/i/indicator-bluetooth/indicator-bluetooth_0.0.6%2b17.10.20170605-0ubuntu3_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/universe/i/indicator-datetime/indicator-datetime_15.10%2b21.04.20210304-0ubuntu1_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/universe/i/indicator-keyboard/indicator-keyboard_0.0.0%2b19.10.20190716-0ubuntu3_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/universe/i/indicator-messages/indicator-messages_13.10.1%2b18.10.20180918-0ubuntu3_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/universe/i/indicator-power/indicator-power_12.10.6%2b17.10.20170829.1-0ubuntu7_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/universe/i/indicator-printers/indicator-printers_0.1.7%2b17.10.20171101-0ubuntu3_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/universe/i/indicator-session/indicator-session_17.3.20%2b21.10.20210613.1-0ubuntu1_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/universe/i/indicator-sound/indicator-sound_12.10.2%2b18.10.20180612-0ubuntu4_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/universe/j/jayatana/jayatana_2.7-0ubuntu6_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/universe/j/jsonrpc-glib/libjsonrpc-glib-1.0-1_3.42.0-1_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/universe/liba/libaccounts-glib/libaccounts-glib0_1.25-1_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/universe/liba/libanyevent-i3-perl/libanyevent-i3-perl_0.17-1_all.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/universe/liba/libanyevent-perl/libanyevent-perl_7.170-2build2_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/universe/liba/libasync-interrupt-perl/libasync-interrupt-perl_1.26-1build2_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/universe/libc/libconfig/libconfig9_1.5-0.4build1_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/universe/libc/libconfuse/libconfuse2_3.3-2_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/universe/libc/libconfuse/libconfuse-common_3.3-2_all.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/universe/libe/libev/libev4_4.33-1_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/universe/libe/libev-perl/libev-perl_4.33-1build2_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/universe/libg/libguard-perl/libguard-perl_1.023-1build7_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/universe/libi/libindicator/indicator-common_16.10.0%2b18.04.20180321.1-0ubuntu5_all.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/universe/libi/libindicator/libindicator3-7_16.10.0%2b18.04.20180321.1-0ubuntu5_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/universe/l/lightdm-gtk-greeter/lightdm-gtk-greeter_2.0.8-2ubuntu1_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/universe/l/lightdm-gtk-greeter-settings/lightdm-gtk-greeter-settings_1.2.2-4_all.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/universe/l/lightdm/liblightdm-gobject-1-0_1.30.0-0ubuntu5_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/universe/l/lightdm/lightdm_1.30.0-0ubuntu5_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/universe/l/lightdm-settings/lightdm-settings_1.5.7-1_all.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/universe/m/moka-icon-theme/moka-icon-theme_5.4.0.4-1_all.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/universe/p/python-i3ipc/python3-i3ipc_2.2.1-2_all.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/universe/p/python-xapp/python3-xapp_2.2.1-2_all.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/universe/p/python-xlib/python3-xlib_0.29-1_all.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/universe/r/rofi/rofi_1.7.1-0.1_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/universe/t/ttf-bitstream-vera/ttf-bitstream-vera_1.10-8.2_all.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/universe/u/ubuntu-touch-sounds/ubuntu-touch-sounds_15.08_all.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/universe/u/unity-greeter/unity-greeter_22.04.1-0ubuntu2_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/universe/u/unity-gtk-module/libunity-gtk2-parser0_0.0.0%2b18.04.20171202-0ubuntu3_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/universe/u/unity-gtk-module/libunity-gtk3-parser0_0.0.0%2b18.04.20171202-0ubuntu3_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/universe/u/unity-gtk-module/unity-gtk2-module_0.0.0%2b18.04.20171202-0ubuntu3_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/universe/u/unity-gtk-module/unity-gtk3-module_0.0.0%2b18.04.20171202-0ubuntu3_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/universe/u/unity-gtk-module/unity-gtk-module-common_0.0.0%2b18.04.20171202-0ubuntu3_all.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/universe/u/unity-settings-daemon/libunity-settings-daemon1_15.04.1%2b21.10.20220207-0ubuntu1_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/universe/u/unity-settings-daemon/unity-settings-daemon_15.04.1%2b21.10.20220207-0ubuntu1_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/universe/u/unity-settings-daemon/unity-settings-daemon-schemas_15.04.1%2b21.10.20220207-0ubuntu1_all.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/universe/x/xcb-util-cursor/libxcb-cursor0_0.1.1-4ubuntu1_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/universe/x/xcb-util-xrm/libxcb-xrm0_1.0-3_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/universe/x/xdotool/libxdo3_3.20160805.1-4_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/universe/x/xdotool/xdotool_3.20160805.1-4_amd64.deb


# pyenv python building dependencies
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl3_3.0.2-0ubuntu1.2_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/libx/libxml2/libxml2_2.9.13%2bdfsg-1ubuntu0.1_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/b/binfmt-support/binfmt-support_2.2.1-2_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/b/binutils/binutils-common_2.38-3ubuntu1_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/b/binutils/libbinutils_2.38-3ubuntu1_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/b/binutils/libctf-nobfd0_2.38-3ubuntu1_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/b/binutils/libctf0_2.38-3ubuntu1_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/b/binutils/binutils-x86-64-linux-gnu_2.38-3ubuntu1_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/b/binutils/binutils_2.38-3ubuntu1_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/g/glibc/libc-dev-bin_2.35-0ubuntu3_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/l/linux/linux-libc-dev_5.15.0-33.34_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/libx/libxcrypt/libcrypt-dev_4.4.27-1_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/r/rpcsvc-proto/rpcsvc-proto_1.4.2-0ubuntu6_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/libt/libtirpc/libtirpc-dev_1.3.2-2build1_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/libn/libnsl/libnsl-dev_1.3.0-2build2_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/g/glibc/libc6-dev_2.35-0ubuntu3_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/g/gcc-12/libcc1-0_12-20220319-1ubuntu1_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/g/gcc-12/libitm1_12-20220319-1ubuntu1_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/g/gcc-12/libatomic1_12-20220319-1ubuntu1_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/g/gcc-11/libasan6_11.2.0-19ubuntu1_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/g/gcc-12/liblsan0_12-20220319-1ubuntu1_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/g/gcc-11/libtsan0_11.2.0-19ubuntu1_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/g/gcc-12/libubsan1_12-20220319-1ubuntu1_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/g/gcc-12/libquadmath0_12-20220319-1ubuntu1_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/g/gcc-11/libgcc-11-dev_11.2.0-19ubuntu1_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/g/gcc-11/gcc-11_11.2.0-19ubuntu1_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/g/gcc-defaults/gcc_11.2.0-1ubuntu1_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/g/gcc-11/libstdc%2b%2b-11-dev_11.2.0-19ubuntu1_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/g/gcc-11/g%2b%2b-11_11.2.0-19ubuntu1_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/g/gcc-defaults/g%2b%2b_11.2.0-1ubuntu1_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/m/make-dfsg/make_4.3-4.1build1_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/d/dpkg/libdpkg-perl_1.21.1ubuntu2_all.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/l/lto-disabled-list/lto-disabled-list_24_all.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/d/dpkg/dpkg-dev_1.21.1ubuntu2_all.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/b/build-essential/build-essential_12.9ubuntu3_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/b/bzip2/bzip2-doc_1.0.8-5build1_all.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/c/curl/libcurl4_7.81.0-1ubuntu1.2_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/c/curl/curl_7.81.0-1ubuntu1.2_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/f/fakeroot/libfakeroot_1.28-1ubuntu1_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/f/fakeroot/fakeroot_1.28-1ubuntu1_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/i/icu/icu-devtools_70.1-2_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/liba/libalgorithm-diff-perl/libalgorithm-diff-perl_1.201-1_all.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/liba/libalgorithm-diff-xs-perl/libalgorithm-diff-xs-perl_0.04-6build3_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/liba/libalgorithm-merge-perl/libalgorithm-merge-perl_0.08-3_all.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/b/brotli/libbrotli-dev_1.0.9-2build6_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/b/bzip2/libbz2-dev_1.0.8-5build1_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/g/glibc/libc-devtools_2.35-0ubuntu3_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/l/llvm-toolchain-14/libllvm14_14.0.0-1ubuntu1_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/universe/l/llvm-toolchain-14/libclang-cpp14_14.0.0-1ubuntu1_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/e/expat/libexpat1-dev_2.4.7-1_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/libf/libfile-fcntllock-perl/libfile-fcntllock-perl_0.22-3build7_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/z/zlib/zlib1g-dev_1.2.11.dfsg-2ubuntu9_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/libp/libpng1.6/libpng-dev_1.6.37-3build5_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/f/freetype/libfreetype-dev_2.11.1%2bdfsg-1build1_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/f/freetype/libfreetype6-dev_2.11.1%2bdfsg-1build1_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/u/util-linux/uuid-dev_2.37.2-4ubuntu3_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/p/pkg-config/pkg-config_0.29.2-1ubuntu3_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/f/fontconfig/libfontconfig-dev_2.13.1-4.2ubuntu5_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/f/fontconfig/libfontconfig1-dev_2.13.1-4.2ubuntu5_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/i/icu/libicu-dev_70.1-2_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/n/ncurses/libncurses-dev_6.3-2_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/universe/n/ncurses/libtinfo5_6.3-2_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/universe/n/ncurses/libncurses5_6.3-2_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/n/ncurses/libncurses5-dev_6.3-2_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/universe/n/ncurses/libncursesw5_6.3-2_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/n/ncurses/libncursesw5-dev_6.3-2_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/libp/libpng1.6/libpng-tools_1.6.37-3build5_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/libp/libpthread-stubs/libpthread-stubs0-dev_0.4-1build2_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/r/readline/libreadline-dev_8.1.2-1_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/s/sqlite3/libsqlite3-dev_3.37.2-2_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl-dev_3.0.2-0ubuntu1.2_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/n/ncurses/libtinfo-dev_6.3-2_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/t/tk8.6/libtk8.6_8.6.12-1build1_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/x/xorg-sgml-doctools/xorg-sgml-doctools_1.11-1.1_all.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/x/xorgproto/x11proto-dev_2021.5-1_all.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/libx/libxau/libxau-dev_1.0.9-1build5_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/x/xorgproto/x11proto-core-dev_2021.5-1_all.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/libx/libxdmcp/libxdmcp-dev_1.1.3-0ubuntu5_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/x/xtrans/xtrans-dev_1.4.0-1_all.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/libx/libxcb/libxcb1-dev_1.14-3ubuntu3_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/libx/libx11/libx11-dev_1.7.5-1_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/libx/libxext/libxext-dev_1.3.4-1build1_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/libx/libxrender/libxrender-dev_0.9.10-1build4_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/x/xft/libxft-dev_2.3.4-1_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/libx/libxml2/libxml2-dev_2.9.13%2bdfsg-1ubuntu0.1_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/libx/libxss/libxss-dev_1.2.3-1build2_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/universe/l/llvm-toolchain-14/llvm-14-runtime_14.0.0-1ubuntu1_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/universe/l/llvm-defaults/llvm-runtime_14.0-55%7eexp2_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/universe/l/llvm-toolchain-14/llvm-14-linker-tools_14.0.0-1ubuntu1_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/libp/libpfm4/libpfm4_4.11.1%2bgit32-gd0b85fb-1_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/universe/l/llvm-toolchain-14/llvm-14_14.0.0-1ubuntu1_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/universe/l/llvm-defaults/llvm_14.0-55%7eexp2_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/libf/libffi/libffi-dev_3.4.2-4_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/p/pygments/python3-pygments_2.11.2%2bdfsg-2_all.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/universe/l/llvm-toolchain-14/llvm-14-tools_14.0.0-1ubuntu1_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/universe/z/z3/libz3-4_4.8.12-1_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/universe/z/z3/libz3-dev_4.8.12-1_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/universe/l/llvm-toolchain-14/llvm-14-dev_14.0.0-1ubuntu1_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/m/manpages/manpages-dev_5.10-1ubuntu1_all.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/p/pyopenssl/python3-openssl_21.0.0-1_all.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/t/tcl8.6/tcl8.6-dev_8.6.12%2bdfsg-1build1_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/t/tcltk-defaults/tcl-dev_8.6.11%2b1build2_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/t/tk8.6/tk8.6_8.6.12-1build1_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/t/tcltk-defaults/tk_8.6.11%2b1build2_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/t/tk8.6/tk8.6-dev_8.6.12-1build1_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/t/tcltk-defaults/tk-dev_8.6.11%2b1build2_amd64.deb
$fetch http://dk.archive.ubuntu.com/ubuntu/pool/main/x/xz-utils/liblzma-dev_5.2.5-2ubuntu1_amd64.deb



