- name: Neovim on debian (and derivatives)
  when: ansible_os_family == "Debian"
  block:
    - name: install opensnitch daemon
      become: yes
      apt:
        deb: https://github.com/evilsocket/opensnitch/releases/download/v1.5.2/opensnitch_1.5.2-1_amd64.deb
    - name: install opensnitch gui
      become: yes
      apt:
        deb: https://github.com/evilsocket/opensnitch/releases/download/v1.5.2/python3-opensnitch-ui_1.5.2-1_all.deb

