# vim: ts=2:sw=2

- name: install dependencies
  become: yes
  apt:
    cache_valid_time: 3600
    pkg:
      - python3-psutil

- name: regolith apt key
  become: yes
  shell:
    cmd: >
      wget -qO - https://regolith-desktop.org/regolith.key |
      gpg --dearmor | sudo tee /usr/share/keyrings/regolith-archive-keyring.gpg > /dev/null
    creates: /usr/share/keyrings/regolith-archive-keyring.gpg 

- name: regolith apt repository
  become: yes
  shell:
    cmd: >
      echo deb "[arch=amd64 signed-by=/usr/share/keyrings/regolith-archive-keyring.gpg]
      https://regolith-desktop.org/release-ubuntu-jammy-amd64 jammy main" |
      sudo tee /etc/apt/sources.list.d/regolith.list
    creates: /etc/apt/sources.list.d/regolith.list

- name: install regolith
  become: yes
  apt:
    update_cache: yes
    install_recommends: yes
    pkg:
      - regolith-desktop
      - regolith-system-ubuntu
      - regolith-compositor-picom-glx
      - regolith-look-gruvbox
#      - regolith-look-solarized-dark
#      - regolith-look-blackhole
#      - regolith-look-nord
#      - regolith-look-nevil
    state: present

- name: install lightdm
  become: yes
  apt:
    state: present
    name: lightdm

# TODO: look into the package regolith-lightdm-config


- name: remove ubuntu-desktop and gdm3
  become: yes
  apt:
    state: absent
    autoremove: yes
    purge: yes
    pkg:
      - ubuntu-desktop
      - ubuntu-desktop-minimal
      - gdm3
      - ubuntu-session
      - unity-greeter

- name: set lightdm as default login manager
  become: yes
  debconf:
    name: lightdm
    question: shared/default-x-display-manager
    value: lightdm
    vtype: select

- name: set default display manager
  become: yes
  copy:
    content: "/usr/sbin/lightdm"
    dest: "/etc/X11/default-display-manager"

- name: enable lightdm
  become: yes
  systemd:
    name: lightdm
    enabled: yes
    state: started

- name: set regolith as default desktop environment user
  lineinfile:
    create: yes
    path: "{{ ansible_env.HOME }}/.dmrc"
    regexp: "Session"
    line: "Session=regolith"

- name: set regolith gruvbox as default look
  lineinfile:
    create: yes
    path: "{{ ansible_env.HOME }}/.config/regolith2/Xresources"
    regexp: "regolith.look.path"
    line: "regolith.look.path: /usr/share/regolith-look/gruvbox"

- name: set screen blank time
  dconf:
    key: "/org/gnome/desktop/session/idle-delay"
    value: "uint32 1800"
    state: present

- name: no location tracking please
  dconf:
    key: "/org/gnome/system/location/enabled"
    value: "false"
    state: present

- name: do not suspend while ac connected and idle
  dconf:
    key: "/org/gnome/settings-daemon/plugins/power/sleep-inactive-ac-type"
    value: "'nothing'"
    state: present

- name: workspaces on all connected displays
  dconf:
    key: "/org/gnome/mutter/workspaces-only-on-primary"
    value: "false"
    state: present

- name: no matter what the locale is we always want 24 hour clock
  dconf:
    key: "/com/canonical/indicator/datetime/time-format"
    value: "'24-hour'"
    state: present

- name: default to danish keyboard layout with us as second option
  dconf:
    key: "/org/gnome/desktop/input-sources/sources"
    value: "[('xkb', 'dk'), ('xkb', 'us')]"
    state: present



