#!/bin/sh
wget -c http://dk.archive.ubuntu.com/ubuntu/pool/universe/p/pigz/pigz_2.6-1_amd64.deb
wget -c http://dk.archive.ubuntu.com/ubuntu/pool/main/b/bridge-utils/bridge-utils_1.7-1ubuntu3_amd64.deb
wget -c http://dk.archive.ubuntu.com/ubuntu/pool/universe/s/shadow/uidmap_4.8.1-2ubuntu2_amd64.deb
wget -c http://dk.archive.ubuntu.com/ubuntu/pool/universe/g/golang-github-containers-image/golang-github-containers-image_5.16.0-3_all.deb
wget -c http://dk.archive.ubuntu.com/ubuntu/pool/universe/g/golang-github-containers-common/golang-github-containers-common_0.44.4%2bds1-1_all.deb
wget -c http://dk.archive.ubuntu.com/ubuntu/pool/universe/o/ostree/libostree-1-1_2022.2-3_amd64.deb
wget -c http://dk.archive.ubuntu.com/ubuntu/pool/universe/g/golang-github-containers-buildah/buildah_1.23.1%2bds1-2_amd64.deb
wget -c http://dk.archive.ubuntu.com/ubuntu/pool/universe/c/catatonit/catatonit_0.1.7-1_amd64.deb
wget -c http://dk.archive.ubuntu.com/ubuntu/pool/universe/c/conmon/conmon_2.0.25%2bds1-1.1_amd64.deb
wget -c http://dk.archive.ubuntu.com/ubuntu/pool/main/r/runc/runc_1.1.0-0ubuntu1_amd64.deb
wget -c http://dk.archive.ubuntu.com/ubuntu/pool/main/c/containerd/containerd_1.5.9-0ubuntu3_amd64.deb
wget -c http://dk.archive.ubuntu.com/ubuntu/pool/universe/g/golang-github-containernetworking-plugins/containernetworking-plugins_0.9.1%2bds1-1_amd64.deb
wget -c http://dk.archive.ubuntu.com/ubuntu/pool/main/y/yajl/libyajl2_2.1.0-3build2_amd64.deb
wget -c http://dk.archive.ubuntu.com/ubuntu/pool/universe/c/crun/crun_0.17%2bdfsg-1.1_amd64.deb
wget -c http://dk.archive.ubuntu.com/ubuntu/pool/main/p/python3-stdlib-extensions/python3-lib2to3_3.10.4-0ubuntu1_all.deb
wget -c http://dk.archive.ubuntu.com/ubuntu/pool/main/p/python3-stdlib-extensions/python3-distutils_3.10.4-0ubuntu1_all.deb
wget -c http://dk.archive.ubuntu.com/ubuntu/pool/universe/w/websocket-client/python3-websocket_1.2.3-1_all.deb
wget -c http://dk.archive.ubuntu.com/ubuntu/pool/universe/p/python-docker/python3-docker_5.0.3-1_all.deb
wget -c http://dk.archive.ubuntu.com/ubuntu/pool/universe/d/dockerpty/python3-dockerpty_0.4.1-2_all.deb
wget -c http://dk.archive.ubuntu.com/ubuntu/pool/universe/d/docopt/python3-docopt_0.6.2-4_all.deb
wget -c http://dk.archive.ubuntu.com/ubuntu/pool/universe/p/python-dotenv/python3-dotenv_0.19.2-1_all.deb
wget -c http://dk.archive.ubuntu.com/ubuntu/pool/main/p/python-attrs/python3-attr_21.2.0-1_all.deb
wget -c http://dk.archive.ubuntu.com/ubuntu/pool/main/s/setuptools/python3-setuptools_59.6.0-1.2_all.deb
wget -c http://dk.archive.ubuntu.com/ubuntu/pool/main/p/pyrsistent/python3-pyrsistent_0.18.1-1build1_amd64.deb
wget -c http://dk.archive.ubuntu.com/ubuntu/pool/main/p/python-jsonschema/python3-jsonschema_3.2.0-0ubuntu2_all.deb
wget -c http://dk.archive.ubuntu.com/ubuntu/pool/universe/t/texttable/python3-texttable_1.6.4-1_all.deb
wget -c http://dk.archive.ubuntu.com/ubuntu/pool/universe/d/docker-compose/docker-compose_1.29.2-1_all.deb
wget -c http://dk.archive.ubuntu.com/ubuntu/pool/universe/a/appstream-glib/libappstream-glib8_0.7.18-2_amd64.deb
wget -c http://dk.archive.ubuntu.com/ubuntu/pool/universe/f/fuse/libfuse2_2.9.9-5ubuntu3_amd64.deb
wget -c http://dk.archive.ubuntu.com/ubuntu/pool/universe/m/malcontent/libmalcontent-0-0_0.10.4-1_amd64.deb
wget -c http://dk.archive.ubuntu.com/ubuntu/pool/universe/f/flatpak/flatpak_1.12.7-1_amd64.deb
wget -c http://dk.archive.ubuntu.com/ubuntu/pool/universe/f/fuse-overlayfs/fuse-overlayfs_1.7.1-1_amd64.deb
wget -c http://dk.archive.ubuntu.com/ubuntu/pool/main/libe/liberror-perl/liberror-perl_0.17029-1_all.deb
wget -c http://dk.archive.ubuntu.com/ubuntu/pool/main/g/git/git-man_2.34.1-1ubuntu1.2_all.deb
wget -c http://dk.archive.ubuntu.com/ubuntu/pool/main/g/git/git_2.34.1-1ubuntu1.2_amd64.deb
wget -c http://dk.archive.ubuntu.com/ubuntu/pool/universe/g/golang-github-containers-dnsname/golang-github-containernetworking-plugin-dnsname_1.3.1%2bds1-2_amd64.deb
wget -c http://dk.archive.ubuntu.com/ubuntu/pool/main/libs/libslirp/libslirp0_4.6.1-1build1_amd64.deb
wget -c http://dk.archive.ubuntu.com/ubuntu/pool/universe/libp/libpod/podman_3.4.4%2bds1-1ubuntu1_amd64.deb
wget -c http://dk.archive.ubuntu.com/ubuntu/pool/universe/libp/libpod/podman-docker_3.4.4%2bds1-1ubuntu1_amd64.deb
wget -c http://dk.archive.ubuntu.com/ubuntu/pool/universe/g/golang-github-containers-toolbox/podman-toolbox_0.0.99.2-2ubuntu1_amd64.deb
wget -c http://dk.archive.ubuntu.com/ubuntu/pool/universe/s/slirp4netns/slirp4netns_1.0.1-2_amd64.deb
wget -c http://dk.archive.ubuntu.com/ubuntu/pool/universe/u/ubuntu-fan/ubuntu-fan_0.12.16_all.deb
