#!/bin/sh
wget -c http://dk.archive.ubuntu.com/ubuntu/pool/main/p/python-babel/python-babel-localedata_2.8.0%2bdfsg.1-7_all.deb
wget -c http://dk.archive.ubuntu.com/ubuntu/pool/main/p/python-babel/python3-babel_2.8.0%2bdfsg.1-7_all.deb
wget -c http://dk.archive.ubuntu.com/ubuntu/pool/main/m/markupsafe/python3-markupsafe_2.0.1-2build1_amd64.deb
wget -c http://dk.archive.ubuntu.com/ubuntu/pool/main/j/jinja2/python3-jinja2_3.0.3-1_all.deb
wget -c http://dk.archive.ubuntu.com/ubuntu/pool/main/p/python-packaging/python3-packaging_21.3-1_all.deb
wget -c http://dk.archive.ubuntu.com/ubuntu/pool/main/p/pycryptodome/python3-pycryptodome_3.11.0%2bdfsg1-3build1_amd64.deb
wget -c http://dk.archive.ubuntu.com/ubuntu/pool/main/p/python3-stdlib-extensions/python3-lib2to3_3.10.4-0ubuntu1_all.deb
wget -c http://dk.archive.ubuntu.com/ubuntu/pool/main/p/python3-stdlib-extensions/python3-distutils_3.10.4-0ubuntu1_all.deb
wget -c http://dk.archive.ubuntu.com/ubuntu/pool/main/d/dnspython/python3-dnspython_2.1.0-1ubuntu1_all.deb
wget -c http://dk.archive.ubuntu.com/ubuntu/pool/main/i/ieee-data/ieee-data_20210605.1_all.deb
wget -c http://dk.archive.ubuntu.com/ubuntu/pool/main/p/python-netaddr/python3-netaddr_0.8.0-2_all.deb
wget -c http://dk.archive.ubuntu.com/ubuntu/pool/universe/a/ansible/ansible_2.10.7%2bmerged%2bbase%2b2.10.8%2bdfsg-1_all.deb
wget -c http://dk.archive.ubuntu.com/ubuntu/pool/universe/p/python-argcomplete/python3-argcomplete_1.8.1-1.5_all.deb
wget -c http://dk.archive.ubuntu.com/ubuntu/pool/main/p/python-jmespath/python3-jmespath_0.10.0-1_all.deb
wget -c http://dk.archive.ubuntu.com/ubuntu/pool/universe/p/pykerberos/python3-kerberos_1.1.14-3.1build5_amd64.deb
wget -c http://dk.archive.ubuntu.com/ubuntu/pool/main/p/python-lockfile/python3-lockfile_0.12.2-2.2_all.deb
wget -c http://dk.archive.ubuntu.com/ubuntu/pool/main/s/simplejson/python3-simplejson_3.17.6-1build1_amd64.deb
wget -c http://dk.archive.ubuntu.com/ubuntu/pool/universe/libc/libcloud/python3-libcloud_3.2.0-2_all.deb
wget -c http://dk.archive.ubuntu.com/ubuntu/pool/universe/p/python-ntlm-auth/python3-ntlm-auth_1.4.0-1_all.deb
wget -c http://dk.archive.ubuntu.com/ubuntu/pool/universe/p/python-requests-kerberos/python3-requests-kerberos_0.12.0-2_all.deb
wget -c http://dk.archive.ubuntu.com/ubuntu/pool/universe/p/python-requests-ntlm/python3-requests-ntlm_1.1.0-1.1_all.deb
wget -c http://dk.archive.ubuntu.com/ubuntu/pool/main/p/python-requests-toolbelt/python3-requests-toolbelt_0.9.1-1_all.deb
wget -c http://dk.archive.ubuntu.com/ubuntu/pool/universe/libs/libselinux/python3-selinux_3.3-1build2_amd64.deb
wget -c http://dk.archive.ubuntu.com/ubuntu/pool/universe/p/python-xmltodict/python3-xmltodict_0.12.0-2_all.deb
wget -c http://dk.archive.ubuntu.com/ubuntu/pool/universe/p/pywinrm/python3-winrm_0.3.0-2_all.deb
