- name: install dependencies for adding ppa
  become: yes
  apt: 
    name: gnupg2

- name: neovim unstable ppa
  become: yes
  apt_repository:
    repo: ppa:neovim-ppa/unstable

- name: install neovim
  become: yes
  apt: 
    name: neovim
    update_cache: yes

- name: alias vim -> nvim
  lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    line: 'alias vim="nvim"'
